---
title: "Projet Tuteuré"
author: "zoé"
date: "2025-02-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
cluster1 <- read.csv('cluster1.csv')
cluster0 <- read.csv('cluster0.csv')
all<- read.csv('tout_cluster.csv')
```


```{r}
library(ggplot2)
library(scales)  # Pour formater les dates

# Assurer que la colonne 'month' est de type Date
cluster1$month <- as.Date(cluster1$month, format="%Y-%m-%d")

# Création du graphique
p <- ggplot(cluster1, aes(x=month, y=WalletFin)) +
  geom_line(aes(group=1), colour="blue") +  # Ajouter une ligne bleue
  geom_point(aes(group=1), colour="red") +  # Ajouter des points rouges
  scale_x_date(labels = date_format("%Y-%m"), breaks = date_breaks("1 month")) +  # Formater et définir les breaks des dates
  labs(title='Wallet Regulation by Month', x='Month', y='WalletFin') +  # Ajouter les titres et les étiquettes
  theme(axis.text.x = element_text(angle=45, hjust=1)) +  # Rotation des étiquettes de l'axe X
  theme_minimal() +  # Thème minimal pour le graphique
  theme(panel.grid.major = element_line(colour = "gray", linetype = "dashed"))  # Ajouter une grille en pointillés

# Afficher le graphique
print(p)

```

